### ISSUE TITLE
[BUG] text extractor folders' names cause sync errors with OneDrive

### ISSUE THREAD

**Issue by balloba** [scambier/obsidian-text-extractor#12]
It seems OneDrive has issues with the folders located in .obsidian/plugins/text-extractor/cache if they are named as single digits like in pic https://imgur.com/a/L5SPOAf

**Comment by Gnopps** [comment]
I'm getting the exact same issue:

![image](https://user-images.githubusercontent.com/16313148/215411631-85a34e4c-a055-4aaa-bb2f-c1c25a2130b1.png)

**Comment by scambier** [comment]
This should be fixed with the latest release. You'll have to clear the cache to delete the invalid folder names. Please reopen if there are still issues with OneDrive
