### ISSUE TITLE
[BUG] Text Extract in Obsidian Android doesn't work 

### ISSUE THREAD

**Issue by ColorCookie-dev** [scambier/obsidian-text-extractor#13]
**Problem description:**
Text Extract on Android Obsidian doesn't work.

It installs and doesn't complain that it's not compatible with my device like Obsidian OCR does.

However when I go to do a search using omnisearch it doesn't detect text from images

*When I hold an image and menu comes up the is an option "Text Extract" however that button doesn't do anything (it doesn't even close the menu signifying that the click was recognised), the phone also doesn't hang*

I would really like to use OCR capabilities from my phone, it will make obsidian very powerful notes app.

![Screenshot_2023-01-31-00-11-36-30_51606159b24eff83e24a54116878fe3e](https://user-images.githubusercontent.com/26321622/215566466-baa323c4-93d1-4de3-8605-595ea36db3ca.jpg)

**Your environment:**

- Plugin version: 0.4.0
- Obsidian version: 1.4.1
- Operating system: Android 13 (realme)
- Number of images/PDFs in your vault (approx.): 0
- Other plugins that may be related to the issue:

**Comment by scambier** [comment]
OCR does not work on mobile, but if you use a syncing solution for your vault, you can use Text Extractor on a computer, and sync its cache folder on your phone.

But there's indeed an issue with the menu, I'll fix that asap.

**Comment by ColorCookie-dev** [comment]
Now the menu at least works on mobile. Only one menu shows up "Extract text into a note"
![Screenshot_2023-01-31-07-52-41-67_51606159b24eff83e24a54116878fe3e](https://user-images.githubusercontent.com/26321622/215644389-f1d61add-a675-4e5f-8352-b0aa0e0bb5c6.jpg)

However now it creates a new note and says this
![Screenshot_2023-01-31-07-48-33-18_51606159b24eff83e24a54116878fe3e](https://user-images.githubusercontent.com/26321622/215645116-011bdee4-9284-44da-aa9a-7fe57dabc8d7.jpg)

Is this the desired behaviour? Or is there a plan to support Android?

**Comment by ColorCookie-dev** [comment]
> OCR does not work on mobile, but if you use a syncing solution for your vault, you can use Text Extractor on a computer, and sync its cache folder on your phone.
> 
> But there's indeed an issue with the menu, I'll fix that asap.

Is there no way to support OCR on mobile. I don't know how tesseract.js works however it's js can it not work on mobile? Or is there something else stopping it from working?

It would really help for it to not depend on syncing with a computer as I'll be importing images on the go and not being able to access ocr search till I come home is disappointing.

**Comment by scambier** [comment]
It _should_ be supported, but I had issues making it work on Android (iirc there was a "device not supported" error or something like that). I'd like to update tesseractjs soon(ish) so I'll try again after that.

**Comment by scambier** [comment]
Won't fix.
