### ISSUE TITLE
[BUG]  Text extractor is using 5gb of ram  and 90% of cpu

### ISSUE THREAD

**Issue by ChrystianSchutz** [scambier/obsidian-text-extractor#18]
Text extractor is using a 5gb of ram  and 90% of cpu.

**Problem description:**
When i load the plugin I have high ram and CPU usage.
Before:
![obraz](https://user-images.githubusercontent.com/3518695/221692263-ba7d0a34-e936-4b2e-8983-208dcf343e88.png)

After:
![obraz](https://user-images.githubusercontent.com/3518695/221692679-cb20ab8a-3c76-4dc7-954f-6eee00034713.png)

**Your environment:**

- Plugin version: 0.4.2
- Obsidian version: 1.1.15 (but before update i had the same issue)
- Operating system: Windows 10
- Number of images/PDFs in your vault (approx.): 250
- Other plugins that may be related to the issue:

**Comment by scambier** [comment]
Those values are not unexpected; I suppose you use Omnisearch, so it will request Text Extractor to read all the PDFs to index them.

Text Extractor will use 70% of your CPU threads to parallelize its work and read several files at once. The results are cached, so once the indexing is done, the CPU/memory load will be back to normal.
