### ISSUE TITLE
Any plans to add latex recognition for images? 

### ISSUE THREAD

**Issue by Zabooby** [scambier/obsidian-text-extractor#2]
Are there any plans to add latex recognition to the plugin? It would basically be adding [mathpix ](https://mathpix.com/)to obsidian which would be super useful to users that work with maths formulas regularly (there's a lot of us)! 

There are a [bunch ](https://github.com/search?q=latex+ocr)of projects on GitHub that do this, would be possible to add this functionality to your plugin?

I've tried mathpix (freemium) and other projects on GitHub (I'm too dumb to set most of them up) end up feeling clunky in my workflow. Having it baked into obsidian would smoothen my workflow so much, not mentioning it being free and open source!

**Comment by scambier** [comment]
Hello, sorry I don't have plans for this yet, as (from what I can see), most of those projects use Python. I want to keep Text Extractor self-contained and mobile-friendly, so all features must either be in JS or Wasm
