### ISSUE TITLE
[BUG]   took a longtime than before to do the text extraction.

### ISSUE THREAD

**Issue by ccchan234** [scambier/obsidian-text-extractor#23]
previously working well.

today cant write to file or to clipboard.
all result in undefined.

i.e. the resulting file only contain:

undefined

then a link to the photo.

thank you

**Comment by ccchan234** [comment]
hi, it worked after a certain time, i will say about 5mins.

may i ask is the OCR process dont locally?

i usually will block obsidian's internet connection by firewall.

today this let me feel that it's not done locally? thanks

**Comment by ccchan234** [comment]
now functions quite well.

strange.... i'll close the ticket and see.

thanks

**Comment by scambier** [comment]
BTW, text extraction is 100% done locally. There are a few parallel worker threads, and it can happen that they're all stuck for some reason. So the process is stalled until the timeout limit kicks in to start working on the next file.

**Comment by ccchan234** [comment]
hi, it always result in undefined if i block obsidian's internet access.

![image](https://user-images.githubusercontent.com/37549409/229990386-68cee2b0-cbea-4fc5-85a6-5422a3fe8c1b.png)

but it worked immediately if i enabled the internet access in firewall.

![image](https://user-images.githubusercontent.com/37549409/229990528-e8140f3d-74c7-4e1c-b857-21f3fe8914c5.png)

could it be something that will cause this?

is the plugin completely open source?

any library it use may need online?

thanks

i am simply a student who striving for survival,
nothing about national security is in my PC, yet.

**Comment by ccchan234** [comment]
well, i did could backup your claim that text extraction 100% local,
because after that i disabled the obsidian's connection, 
and render ANOTHER file, it success.
![image](https://user-images.githubusercontent.com/37549409/229991142-3840c45b-4838-43d2-97cc-9054fc9ab70c.png)

quite strange, but i'll still use it.
thanks for that.

**Comment by scambier** [comment]
I see those are screenshots from a phone, and Text Extractor does not work on phones. It relies on cache synchronization with a computer to get the text values. See [this point](https://github.com/scambier/obsidian-text-extractor#cache--sync) in the readme.

All the source code is available on this repository. Dependencies are also open source; OCR relies on [Tesseract.js](https://tesseract.projectnaptha.com/).

**Comment by ccchan234** [comment]
1. hi, those screenshot are took from phones, but then i moved them onto windows machines.

2. i saw a "clear cache" button but after click it seems not working. i tried uninstall the plugin and re-install but the cache seems still there.  i will try uninstall the plugin, then delete the plugin folder under /.obsidian and then reinstall

so far it's working for me i'll stay /w this, thanks

**Comment by ccchan234** [comment]
> I see those are screenshots from a phone, and Text Extractor does not work on phones. It relies on cache synchronization with a computer to get the text values. See [this point](https://github.com/scambier/obsidian-text-extractor#cache--sync) in the readme.
> 
> All the source code is available on this repository. Dependencies are also open source; OCR relies on [Tesseract.js](https://tesseract.projectnaptha.com/).

ok saw your point on cache,
may be it's malfunctioning causing result in "undefined".
may be i'll powerwash everything later, thanks

**Comment by ccchan234** [comment]
> 1. hi, those screenshot are took from phones, but then i moved them onto windows machines.
> 2. i saw a "clear cache" button but after click it seems not working. i tried uninstall the plugin and re-install but the cache seems still there. i will try uninstall the plugin, then delete the plugin folder under /.obsidian and then reinstallthanks
> 
> so far it's working for me i'll stay /w this, thanks
