### ISSUE TITLE
[BUG] Image is uploaded to OSS, this ocr is invalid

### ISSUE THREAD

**Issue by Yinlin124** [scambier/obsidian-text-extractor#27]
**Problem description:**

When the image is uploaded to OSS, this plugin becomes invalid, and the image is in local format and the plugin can be used normally.

Eg:
![image](https://user-images.githubusercontent.com/91457024/235609335-cbc3d7d2-1230-42dd-808d-1b7ba1dea843.png)
This picture is uploaded，the plugin is invalid.

![image](https://user-images.githubusercontent.com/91457024/235609535-6da5095f-2cf4-4afa-993f-508fe4e81038.png)
The local file is valid.

![image](https://user-images.githubusercontent.com/91457024/235609810-fc89855d-4347-4074-a0e0-142a02018ace.png)
From the search results, it can be seen that ocr is only effective for local images, and uploaded images do not work.And no errors were output in the console

This issue may also be related to this issue：
https://github.com/scambier/obsidian-text-extractor/issues/22
 
**Your environment:**

- Plugin version:0.4.3
- Obsidian version:v1.1.16
- Operating system: Windows 10 19044.2846
- Number of images/PDFs in your vault (approx.): 1376
- Other plugins that may be related to the issue: No

**Comment by scambier** [comment]
This is a non-feature, not a bug; Text Extractor only works on local files.

**Comment by Yinlin124** [comment]
Are there any plans to launch this feature in the future? Beacuse image uploading is very common in .md notes

**Comment by scambier** [comment]
Probably not, mainly because processing random files from the internet could lead to security issues. That's not the kind of responsibility I want to deal with for a hobby project 🤷‍♂️
