### ISSUE TITLE
[BUG] No Context Menu & No Search

### ISSUE THREAD

**Issue by DarkByteZero** [scambier/obsidian-text-extractor#29]
**Problem description:**

Text Extractor has no context menu, and Omnisearch won't Index anything from .png files.
![CleanShot 2023-05-20 at 06 34 21](https://github.com/scambier/obsidian-text-extractor/assets/22873369/3dcac0c2-a0cb-4fcc-ad5e-0b377a556858)

I get following Errors:

![image](https://github.com/scambier/obsidian-text-extractor/assets/22873369/fa30de44-7f6f-4b78-9100-2ef32ab80f55)

Maybe it can't create the cache folder ?

**Your environment:**

- Plugin version: 0.4.4
- Obsidian version: v1.2.8
- Operating system: MacOS 13.3.1 (a)
- Number of images/PDFs in your vault (approx.): 15
- Other plugins that may be related to the issue: none
- Vault is in iCloud Drive

**Comment by DarkByteZero** [comment]
ok, i created the cache folder inside the plugin folder and it works. I have no idea why it was not there, maybe check in the code if the folder is present and if not, create it instead of crashing.

**Comment by scambier** [comment]
Caused by the function converting the old cache paths to new paths - Fixed
