### ISSUE TITLE
[BUG] Does not support Simplified Chinese.

### ISSUE THREAD

**Issue by yongnianliu** [scambier/obsidian-text-extractor#30]
input image
![image](https://github.com/scambier/obsidian-text-extractor/assets/6042007/d47c3ae4-da73-4625-82bd-ef5df8eb9f0d)

OCR result(Extract Text to clipboard)
"E a 10F 1 招 HIERR a65 2 zz t 仁 3 RtSI0FETEN E 4 PEIHRSGRSKah E B s 沥"

my settings.
![image](https://github.com/scambier/obsidian-text-extractor/assets/6042007/30b520b7-366d-4c68-accf-074718343e00)

![image](https://github.com/scambier/obsidian-text-extractor/assets/6042007/0105df36-4bb4-436a-bf2a-23cf4a8b7031)

**Problem description:**
Adding an image containing Simplified Chinese resulted in text recognition that does not match the content of the image. The recognized content appears more like garbled characters.

**Your environment:**
Windows 11 Professional x64 22H2

- Plugin version:0.4.5
- Omnisearch Plugin version:1.14.0
- Obsidian version:v1.3.4
- Operating system: win11 x64
- Number of images/PDFs in your vault (approx.):3
- Other plugins that may be related to the issue:no

**Comment by yongnianliu** [comment]
This is a fantastic plugin, I hope it can support Simplified Chinese.

**Comment by scambier** [comment]
Probably the same issue as [#1](https://github.com/scambier/obsidian-text-extractor/issues/1#issuecomment-1400719519). Is the behavior different if you remove "eng" from the list of OCR Languages, clear the cache, and re-extract?

**Comment by yongnianliu** [comment]
Thank you for your reply. I tried to set only Simplified Chinese and cleared the cache, but the problem still exists. It seems that it is not the same issue as #1 .

**Comment by Onkitova** [comment]
@yongnianliu try this:

1. Go to   

> *your_vault_folder*\\.obsidian\plugins\text-extractor

2. Open data.json file and edit it to look like this
![image](https://github.com/scambier/obsidian-text-extractor/assets/119720012/ed08bdc1-5922-4717-9f9e-fcca35b4407a)
3. Open Obsidian, clear cache of Text Extractor and then try to OCR-something into text note.

Solution above seems to work for me with similar issue https://github.com/scambier/obsidian-text-extractor/issues/1. 

And please, share a feedback over here if such temporal solution also works for your eng+chi_sim language combination as it works for eng+rus.

**Comment by scambier** [comment]
@yongnianliu the workaround mentioned by Onkitova has been fixed in the latest release. Could you update the plugin and report if this fixes your issue? Thanks :)

**Comment by yongnianliu** [comment]
Yes,It works.Sorry for the late reply. Thanks@scambier @Onkitova
