### ISSUE TITLE
[BUG] Doesn't work offline

### ISSUE THREAD

**Issue by Onkitova** [scambier/obsidian-text-extractor#31]
**Problem description:**
Text Extractor doesn't work for images without internet connection. PDF extracts fine, however (I guess due to the different backend library). While offline, the result is:
![image](https://github.com/scambier/obsidian-text-extractor/assets/119720012/6765d3ad-ba71-4b0d-8215-7fbc41027917)
![image](https://github.com/scambier/obsidian-text-extractor/assets/119720012/e84a8a67-0bf3-4541-bff2-6132097ae0c2)

1. Why so? Does text extractor process images via some web api on a remote server?

**Your environment:**

- Plugin version: 0.4.5
- Obsidian version: 1.3.5
- Operating system: Windows 11 22h2
- Number of images/PDFs in your vault (approx.): ~10
- Other plugins that may be related to the issue: -

**Comment by scambier** [comment]
> While offline, the result is:

Is the result different when online? Text Extractor uses a local copy of TesseractJS for OCR, there's no external API call.

I tried it on your image (while offline) and got the following text :
> ' Getting Ready to use Obsidian Blectures + 42min v Basics of Obsidian 55 lectures + 2hr 25min ~ Obsidian for Notion Users 6lectures - 24min © Whatis Make.md plugin 0326 @ Creating a New Vauit o110 @ Installing Make.md plugin otts @ Basic Text Formatting 0559 @ Spaces and Folders 08:36 @ Spaces and Folders View 0320

Could you please try the following steps:
- Open the developer console: `ctrl+shift+i` then open the "Console" tab
- Make sure that Text Extractor has "eng" as its OCR language
- Clear its cache
- Re-extract text for this image
- Report any error that pops up in the console

**Comment by Onkitova** [comment]
>Is the result different when online?

Yes, of course.

>I tried it on your image (while offline) and got the following text :

Same for me. When online.
>Report any error that pops up in the console

1 error exactly:
>Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://unpkg.com/tesseract.js@v3.0.3/dist/worker.min.js' failed to load.

**Comment by scambier** [comment]
Ok I managed to reproduce the issue after a restart 🤔

I'll try to patch this asap

**Comment by scambier** [comment]
Another problem is that, additionally to the worker, Tesseract also downloads the language(s) data if not cached. It's not really feasible to bundle _all_ the languages for offline use.

**Comment by Onkitova** [comment]
> Another problem is that, additionally to the worker, Tesseract also downloads the language(s) data if not cached. It's not really feasible to bundle _all_ the languages for offline use.

Okay, then just tell me how can I move cached scripts and language-specific files between PCs (some of which doesn't have network access 24/7) after its initial download and I will close this issue. I guess it is located somewhere in 
%APPDATA%\Obsidian\
but I am not sure where exactly.

And, I suppose, you should mention such web-dependent circumstances somewhere in plugin's description in order to prevent issues like this in the future, as long as pre-caching everything is not the way.

**Comment by scambier** [comment]
> Okay, then just tell me how can I move cached scripts

Honestly no idea. The cache is managed by Electron so no idea where or how it works, sorry.
