### ISSUE TITLE
[??] What's up with the text-extractor cache

### ISSUE THREAD

**Issue by Smitty010** [scambier/obsidian-text-extractor#32]
Today I was backing up my obsidian and noticed the text extractor (which you say you no longer support) had generated 19,716 json files on the 23rd. including the following example:
```
{"path":".obsidian/plugins/text-extractor/cache/3424049d9ade87b1d9607cf08a953f0e.json","text":"PR— x| T R S— x LA - o x (Eoomiatn) 75 D-\\orejecttestss prtnen . \\sssistantsotinaust oy Founs st it & et assu. 597001 Loading aase fron “3:\\\\Projects\\Eumonia\\\\LUN\\gpHL-gt4ati-5-v. & groony. Vectorstore created at 0:\\projects\\tasts\\ed 39t3_podel_Load: n_vecab = 5040 (Eooniatn) 75 DAorasecttestes | e oo oo tons b - 499 oo -tens s - 36 ot moa-Aows n-aver - 28 ot s tosts et - 84 [t 591 e et s ot sz + 40105 8 ot mo-lons v 3hF size © £96.00 18 Tt mod ot e e oo toss sosl site = S35 4 on Seniors = 285 Enten & qary: Matis the projct folder strocture? (Use th cuntext provided to bils he & ) e siva pisces of cod are rtated to 2 Gjango ppkication, specificaly its sottings ng irsctorin uaed in Goelopaent. pecess calLad DIAS\". Thie patns provich access fo sati il Tike Lasge o stytesnets. Thire 1s ho aertion about any projct FaNse strcture Sutsise his cantxt provided 3o camnet ansrr. he testion vith what Anforastion slare 33 € ey n b reLavant wEhaut furhar ELRLLE o SRSt exscRly Yo B8 30k 18 ko (33 et e, version umbar k). Ente & quary: Mt versicn of Django the roject uses? o hich diretory does your Oange sppLication's sottings file roide in and b o they L3t it static Fles Like 1sags or SHYLISGtS Shat y Be prasen n this Mesite: ring Yo praject 2 S5 55 ety revated 1 anapiog dopadencies o giFterent varians 30 Fort MALigs snviroretnts (o0, chveLapeen a1 prosuetian) . 1f no sentioned iy seher Hing ite Lacation for Stetic Fits nsmapesent Enten qary: Are thare sny soets crestes i tho appLication ido sare context anc/on inforsation sbout this particular Diang project's architecture (if iy I soes ke th cusstion s aaking fon uidance o ow to crate an APT et In Pyt 74\"S0 o, weh suppes 8 aay be p0ss 514 10 U Diange REST Frasteark o ancthar 5 inita Vibrary intead if Gosired by Tabifyin sone parts acsardinly and reveing th rest ¢ Fonerk packase fron d3angorstfranenak 33 SESHRStvG far GRSV APL GNP,","libVersion":"0.2.2","langs":"eng"}
```
My basic question is WTF

**Comment by scambier** [comment]
If the "WTF" means "_why are there so many files?_", you're supposed to have 1 cache file per treated document. If you still have 2-letters folders, you can safely delete them (they're remnants of the old cache system).

If the "WTF" means "_I don't understand what's the gibberish in those json files_", that's just how the library read the file, and sometimes it doesn't work super well.

**Comment by Smitty010** [comment]
I should never write emails first thing in the morning before caffeine.
Apologies

There were no files (and no cache) 2 days ago.  Now there are now 19,716
files (mostly less than 1KB).  All have creation dates yesterday or today.
Backing up 19k files to a network drive over wifi is pretty slow (which is
why I noticed; do these get synced with my other devices or are they
recreated there). There are no 2 character folders (or any other folder in
the cache - .obsidian\plugins\text-extractor\cache).

What did I do to "treat" that many files?  should there have been that many
from the beginning?  Can you give me some idea what they represent or what
"treat"ing means?  I'm beginning to suspect there may be some OCR in there.

I really like omnisearch.  I'm just not sure what these have to do with it.

Scott

**Comment by scambier** [comment]
> I'm beginning to suspect there may be some OCR in there.

Well, the files are from the Text Extractor plugin, and they are indeed cache from images OCR and PDF text extraction.

Text Extractor works as a dependency for Omnisearch to index images and PDFs
![image](https://github.com/scambier/obsidian-text-extractor/assets/3216752/a83ad798-1e3f-4010-9241-75b84a6dfa9d)

Each time a file is "treated" (OCRed or extracted), the result is saved in a small cache file, and those files can be synced between your devices. If you have 19k files, that means you have 19k images or PDFs in your vault.

Edit: "You" didn't do anything specific to treat those files. It's actually Omnisearch that automatically asked Text Extractor during its indexing process.

**Comment by Smitty010** [comment]
I have no trouble believing there are 19k images in my vault.  What caught me off guard is that I don't think I changed anything, but the JSON files weren't there before, but now they are.  I guess I will stop worrying about it.

**Comment by Smitty010** [comment]
I think I figured out the problem.  But, I looked and it looks like there was a commit (https://github.com/scambier/obsidian-omnisearch/issues/254 - Fixed Text Extractor indexing when disabled in settings) a few hours ago that will probably fix the problem.  I'll clear my cache.

**Comment by Smitty010** [comment]
And, I still really like omnisearch.  It just works

**Comment by scambier** [comment]
> I think I figured out the problem. But, I looked and it looks like there was a commit ([scambier/obsidian-omnisearch#254](https://github.com/scambier/obsidian-omnisearch/issues/254) - Fixed Text Extractor indexing when disabled in settings) a few hours ago that will probably fix the problem. I'll clear my cache.

Aah yep, that might be it 👍
