### ISSUE TITLE
[Feature request] Allow numerical values for Results weighting.

### ISSUE THREAD

**Issue by YousufSSyed** [scambier/obsidian-text-extractor#33]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I just think its a good idea to add number text boxes to the results weighting section to enter in numbers if users don't want to use the sliders.

**Comment by scambier** [comment]
The sliders are there to limit the range of possibles values, and not break the algorithm with disproportionate weights. There's no real advantage (I think) to have text inputs instead of sliders.
