### ISSUE TITLE
Text Extraction Dependency

### ISSUE THREAD

**Issue by khesed** [scambier/obsidian-text-extractor#36]
I'm unclear on how the Obsidian plugin system works with regard to dependencies, but I'm curious what your thoughts are on using a general library like [textract](https://www.npmjs.com/package/textract) for text extraction?

**Comment by scambier** [comment]
There are different approaches regarding dependencies, but basically anything goes.

The philosophy I have with Text Extractor is to keep it self-contained, so dependencies must run in JS (either pure JS or wasm). Some plugins like [Obsidian OCR](https://github.com/MohrJonas/obsidian-ocr) need external dependencies to be installed on the host computer. That's also how the textract library works.
