### ISSUE TITLE
[BUG] Inserts extraneous spaces in PDF

### ISSUE THREAD

**Issue by L1Z3** [scambier/obsidian-text-extractor#41]
**Problem description:**

There are a few PDFs I have that have embedded text that Text Extractor fails to properly extract in the correct format. For instance, see [this PDF](https://github.com/scambier/obsidian-text-extractor/files/12673328/03-sockets-notes.pdf). For many of the slides, Text Extractor inserts numerous extraneous spaces. For instance, on page 6 of this PDF, Text Extractor extracts this line:
`N e tw o rk s o c k e ts a r e f i l e d e s c ri p to rs to o`
whereas copying and pasting directly from the PDF within Obsidian or another PDF viewer gives:
`Network sockets are file descriptors too`

**Your environment:**

- Plugin version: 0.4.6
- Obsidian version: 1.4.13
- Operating system: Fedora 38
- Number of images/PDFs in your vault (approx.): 6
- Other plugins that may be related to the issue: N/A

**Comment by L1Z3** [comment]
Update: I have found a workaround to this issue. If I load the PDF into [Xournal++](https://xournalpp.github.io/) and then export it as a PDF from there, Text Extractor suddenly has no problems. I suspect the issue has something to do with how the original app that produced the PDF encoded the text and that Xournal++ converts it to some different format, but this is just speculation.

**Comment by L1Z3** [comment]
In principle, the behavior Xournal++ uses to export the PDF could be replicated in an Obsidian plugin, which could be a very hacky way to workaround this issue in a semi-automated way. I have also encountered the issue in #7 in which some PDFs fail to extract altogether, and using Xournal++ to re-export such PDFs also seems to allow them to have their text extracted for me (at least after a couple "Clear cache for this file" -> "Extract text to clipboard" cycles).

**Comment by jh0274** [comment]
could be linked to this:

https://bugs.ghostscript.com/show_bug.cgi?id=696116

and:

https://github.com/tesseract-ocr/tesseract/issues/373  ?

**Comment by scambier** [comment]
Nope, PDFs are not OCR'ed, just processed by https://github.com/jrmuizel/pdf-extract

**Comment by jh0274** [comment]
ah! of course.. thanks

 i'm getting this problem for 2 things:
- when i extract text from pdf
- when i search using Omnisearch (which uses text-extractor i believe?)

**Comment by scambier** [comment]
Yes, Omnisearch uses data from Text Extractor so that's expected
