### ISSUE TITLE
Failed to load plugin text-extractor

### ISSUE THREAD

**Issue by agkozak** [scambier/obsidian-text-extractor#42]
**Problem description:**

Starting today, on both iOS and iPadOS 17.0.2, when I first open Obsidian, I get the error message

    Failed to load plugin text-extractor

**Your environment:**

- Plugin version: 0.4.7
- Obsidian version: 1.4.8 (107)
- Operating system: iOS 17.0.2 and iPadOS 17.0.2
- Number of images/PDFs in your vault (approx.): 150
- Other plugins that may be related to the issue:

**Comment by agkozak** [comment]
I just used BRAT to load 0.4.6 -- that version still seems to work.

**Comment by scambier** [comment]
Plugin failure: text-extractor TypeError: Cannot read properties of undefined (reading 'Buffer')
    at eval (plugin:text-extractor:4462:43)
    at anonymous (plugin:text-extractor:4488:2)
    at e.<anonymous> (app.js:1:1971969)
    at app.js:1:236934
    at Object.next (app.js:1:237039)
    at a (app.js:1:235757)

**Comment by scambier** [comment]
Should be fixed with 0.4.8
