### ISSUE TITLE
[BUG] Majority of PDFs not extracting text

### ISSUE THREAD

**Issue by DevDinosaur** [scambier/obsidian-text-extractor#45]
**Problem description:**

Hi, I think this is the first time I've ever posted or asked for help on github. Forgive me if I break a standard. I have searched in and outside of github for help and no solution has been found.

I have about 45 PDF files I'm trying to be able to search in with Omnisearch, but only a handful are yielding any results. When I try to just extract the text to clipboard for these, the console outputs "*Text Extractor - Could not extract text from*…". If I extract to a new note, it just creates a new note with the PDF embedded in the note.

I have tried re-exporting the file as a PDF or saving as a PDF from different programs with no changes. I saw someone's comment about doing that with Xournal++, but unfortunately I can't install that on my computer (company restrictions). I made sure Omnisearch and Text Extractor were up-to-date. I also cleared cache and re-indexed everything. Also, if I just highlight and copy text in the PDF to paste elsewhere, it has no problem doing that.

This is an example PDF from the collection. It is a free book download. 
[Always-be-Ready.pdf](https://github.com/scambier/obsidian-text-extractor/files/13400151/Always-be-Ready.pdf)

**Your environment:**

- Plugin version: 1.19.0 (Omnisearch) | 0.4.8 (Text Extractor)
- Obsidian version: 1.4.16
- Operating system: Windows 10
- Number of images/PDFs in your vault (approx.): 45
- Other plugins that may be related to the issue: n/a

**Comment by scambier** [comment]
It's an issue with the underlying library: some files work, some don't 🤷‍♂️ https://github.com/scambier/obsidian-text-extractor/discussions/21

**Comment by DevDinosaur** [comment]
> It's an issue with the underlying library: some files work, some don't 🤷‍♂️ #21

Thanks for the reply. I did miss that thread.
