### ISSUE TITLE
[Feature request] Add romanian language support

### ISSUE THREAD

**Issue by PruteanuVlad** [scambier/obsidian-text-extractor#46]
Hello from Romania! 
Would greatly appreciate it if you added support for romanian, or provide a framework for users to do so.

**Comment by scambier** [comment]
Hello, it looks like "ron" is the language you should select in the list for Romanian :)

https://github.com/naptha/tesseract.js/blob/4970ceaabbbe10eacef1f201182e23b9b07a8c35/src/constants/languages.js#L82

**Comment by PruteanuVlad** [comment]
Thank you for the quick response and sorry for not catching that. I saw that option but a superficial Google search showed me some unrelated results.
Thank you once again!

**Comment by scambier** [comment]
By the way, I just found the proper language reference: https://tesseract-ocr.github.io/tessdoc/Data-Files-in-different-versions.html
